### ISSUE TITLE
not so happy with the auto-configured turnserver.conf 

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-coturn#1]
just tried this repository.
The auto-generated turnserver.conf is lacking things like realm, external-ip. The env variable REALM=myrealm.tld isn't understood because it is written as
`myrealm.tld`
instead of 
`realm=myrealm.tld`

from outside, I can't get a connection while when trying to connect to the internal address, I can connect. This needs more investigating - probably my docker-compose is missing something.

**Comment by tiredofit** [comment]
More than likely I've screwed this up - It has been used in very limited fashion in our environment for a local project yet didn't get much more love after that. I'm definitely open to any mods so that its workable for your environment, or if you have some working config to share I can work it in for you.

**Comment by joergmschulz** [comment]
Hmmm. Will try and submit CRs.
